name: Convert Notebooks to HTML and Deploy to GitHub Pages

on:
  push:
    branches:
      - main 

jobs:
  convert-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r "Rule Notebooks/requirements.txt"

      - name: Convert notebooks to HTML with hidden code
        run: |
          # Ensure the custom template file is available
          cp hide_code.tpl "Rule Notebooks/"
          python convert_notebooks.py
        
      - name: Add navigation to HTML files
        run: |
          python add_navigation.py

      - name: Add HTML files to the repository
        run: |
          git config --global user.email "summayah.waseem@gmail.com"
          git config --global user.name "sumwas"
          git add "Rule Notebooks"
          git commit -m "Convert notebooks to HTML and deploy"

      - name: Push changes to GitHub
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/sumwas/BIM-Casestudy.git HEAD:main

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "Rule Notebooks"
